print("Welcome to Machine Learning!!")
print("Select a Algorithm")
print("1. Simple Linear Regression")
print("2. Multiple Linear Regression")
print("3. Polynomial Linear Regression")
print('4. non Linear Regression')
c = int(input("Enter your choice: "))
